package dev.saurabh.docintel.service;
import dev.saurabh.docintel.api.*;import dev.saurabh.docintel.domain.*;import dev.saurabh.docintel.repo.*;import jakarta.persistence.EntityNotFoundException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.text.Normalizer;import java.util.*;import java.util.stream.Collectors;
@Service public class DocumentService{
 private static final int CHUNK_SIZE=1200;private final DocumentRepository documents;private final DocumentChunkRepository chunks;private final EncryptionService encryption;
 public DocumentService(DocumentRepository d,DocumentChunkRepository c,EncryptionService e){documents=d;chunks=c;encryption=e;}
 @Transactional public DocumentView ingest(String owner,IngestDocumentRequest req){String normalized=Normalizer.normalize(req.text(),Normalizer.Form.NFKC);List<String> parts=chunk(normalized);String hash=sha256(normalized);var doc=documents.save(new DocumentRecord(owner,req.title(),req.sourceName(),hash,parts.size()));for(int i=0;i<parts.size();i++){var sealed=encryption.seal(parts.get(i).getBytes(StandardCharsets.UTF_8));chunks.save(new DocumentChunk(doc,i,sealed.nonce(),sealed.ciphertext()));}return DocumentView.of(doc);}
 @Transactional(readOnly=true) public List<DocumentView> list(String owner){return documents.findTop100ByOwnerSubjectOrderByCreatedAtDesc(owner).stream().map(DocumentView::of).toList();}
 @Transactional(readOnly=true) public List<SearchHit> search(String owner,String query){Set<String> terms=Arrays.stream(query.toLowerCase(Locale.ROOT).split("[^\\p{L}\\p{N}]+" )).filter(s->s.length()>1).collect(Collectors.toSet());if(terms.isEmpty())return List.of();List<SearchHit> hits=new ArrayList<>();for(var doc:documents.findTop100ByOwnerSubjectOrderByCreatedAtDesc(owner)){for(var chunk:chunks.findByDocumentIdOrderByChunkIndex(doc.id)){String text=new String(encryption.open(chunk.nonce,chunk.ciphertext),StandardCharsets.UTF_8);String lower=text.toLowerCase(Locale.ROOT);int score=(int)terms.stream().filter(lower::contains).count();if(score>0)hits.add(new SearchHit(doc.id,doc.title,chunk.chunkIndex,score,doc.sourceName+" · chunk "+(chunk.chunkIndex+1),excerpt(text,terms)));}}return hits.stream().sorted(Comparator.comparingInt(SearchHit::score).reversed()).limit(20).toList();}
 @Transactional public void delete(String owner,UUID id){var doc=documents.findByIdAndOwnerSubject(id,owner).orElseThrow(()->new EntityNotFoundException("Document not found"));documents.delete(doc);}
 private List<String> chunk(String text){List<String> out=new ArrayList<>();for(int i=0;i<text.length();i+=CHUNK_SIZE)out.add(text.substring(i,Math.min(text.length(),i+CHUNK_SIZE)));return out.isEmpty()?List.of(""):out;}
 private String excerpt(String text,Set<String> terms){String lower=text.toLowerCase(Locale.ROOT);int at=terms.stream().mapToInt(lower::indexOf).filter(i->i>=0).min().orElse(0);int start=Math.max(0,at-100),end=Math.min(text.length(),start+280);return text.substring(start,end).replaceAll("\\s+"," ").trim();}
 private String sha256(String text){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}

